language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - coverage run -m unittest
  - coverage report --include="sigpy/*"
notifications:
  email: false
after_success:
  - coveralls
