language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - coverage run -m unittest
  - coverage report --include="sigpy/*"
notifications:
  email: false
after_success:
  - coveralls
